[build]
  command = "yarn build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "#custom"
  command = "yarn dev"
  targetPort = 3000
  port = 8888

[[redirects]]
  from = "/submit"
  to = "https://forms.gle/FcKAxdto2YHTRjpm7"
  status = 302
  force = true